#!/bin/bash

set -ex

usage="$(basename "$0") [-h] [-s SPEC] [-r REPO]

where:
 -h       show this help text

 -s SPEC  builds using given SPEC. Here, SPEC basename is only
	  expected and should be allocated under rpm/ subfolder
	  of the sources. By default, the first SPEC in rpm/
	  subfolder is used

 -r REPO  additional repository that is needed to fetch packages
	  required for building SPEC
"


# Builds RPMs from sources found in /source
SRCDIR=source
BDIR=/builder
RPMTARGET=`cat /etc/rpmtarget`

# use / as a base
cd /

RPMSRCDIR=$BDIR/rpmbuild/SOURCES
RPMSPECDIR=$BDIR/rpmbuild/SPECS
RPMDIR=$BDIR/rpmbuild/RPMS

specs=( $SRCDIR/rpm/*.spec )
SPEC="${specs[0]}"

# handle options
while getopts 'sr:h' opt; do
  case "$opt" in
      s)
	  SPEC=$SRCDIR/rpm/$OPTARG
	  ;;

      r)
	  arg="$OPTARG"
	  echo "Adding repository $arg"
	  zypper ar --gpgcheck-allow-unsigned $arg repo-$OPTIND
	  echo
	  ;;

      ?|h)
	  echo "$usage"
	  exit 0
	  ;;
  esac
done
shift "$(($OPTIND -1))"

# check if we have spec to build
if [ ! -f $SPEC ]; then
    echo "Cannot find any SPEC files in $SRCDIR/rpm"
    echo
    echo "$usage"
    exit -1
fi

SPECBNAME=`basename $SPEC`
echo Building $SPECBNAME

# install dependencies
rpm-install-build-deps $SPEC

# determine source name
SOURCE=$(rpmdev-spectool --source 0 $SPEC | cut -f2 -d" ")
echo Packing sources into $SOURCE

# prepare RPM builder directories
chown -R builder $BDIR
su builder rpmdev-setuptree

SRCBASE=`rpmspec -q --srpm --qf "%{name}-%{version}\n" $SPEC`
TAROPTS="--exclude-vcs --exclude $SRCDIR/RPMS --exclude $SRCDIR/rpm --transform s/^source/$SRCBASE/"

# pack main sources
if [[ $SOURCE = *.tar.gz ]]; then
    tar cf - $TAROPTS $SRCDIR/ | gzip -1 -n > $RPMSRCDIR/$SOURCE
elif [[ $SOURCE = *.tar.bz2 ]]; then
    tar cf - $TAROPTS $SRCDIR/ | bzip2 -1 -c > $RPMSRCDIR/$SOURCE
elif [[ $SOURCE = *.tar.xz ]]; then
    tar cf - $TAROPTS $SRCDIR/ | xz -0 -c > $RPMSRCDIR/$SOURCE
else
    echo "Unknown file extension for sources: $SOURCE"
    exit 2
fi

# copy all other sources and SPEC from rpm subfolder
cp $SRCDIR/rpm/* $RPMSRCDIR/
cp $SPEC $RPMSPECDIR

# set RPATH check to none as the use in SFOS leads to failure in check
QA_RPATHS=$(( 0x0001|0x0002|0x0008|0x0010 ))

# start the build
su builder -c \
   "QA_RPATHS=$QA_RPATHS rpmbuild -bb \
       --define '_srcdefattr (-,root,root)' \
       --target=$RPMTARGET --nosignature \
       $RPMSPECDIR/$SPECBNAME"

# rpmlint
su builder -c "rpmlint $RPMDIR/"

# copy RPMS to source RPMS subfolder
mkdir -p $SRCDIR/RPMS
cp $RPMDIR/*/* $SRCDIR/RPMS/
chown -R `stat -c '%u:%g' $SRCDIR/.` $SRCDIR/RPMS
chmod +r $SRCDIR/RPMS/*

echo "
Ready
"
