#!/bin/bash

set -ex

if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

SFOS_ARCH=$1
RELEASE=$2

case "$SFOS_ARCH" in
    "i486")
	RPMTARGET=i486-meego-linux
	;;
    "aarch64")
	RPMTARGET=aarch64-meego-linux
	;;
    "armv7hl")
	RPMTARGET=armv7hl-meego-linux
	;;
    *)
	echo "Unknown architecture specified:" "$SFOS_ARCH"
	exit -1
esac

INSTALL_ROOT=/sfos

# packages that have to be installed later:
# - git (otherwise %posttrans script 'filesystem' will fail on armv7hl

PACKAGES="
atruncate
attr
basesystem
gcc-c++
gnu-bash
gnu-coreutils
gnu-cpio
gnu-diffutils
gnu-findutils
gnu-grep
gnu-gzip
gnu-sed
gnu-tar
gnu-which
deltarpm
file
jolla-ca
kbd
make
meego-rpm-config
net-tools
passwd
pigz
procps-ng
psmisc-tools
python3-pip
rootfiles
rpm-build
rpmlint
sailfish-ca
shadow-utils
util-linux
xdg-utils
zypper
"

# switch arch to the desired one
echo "arch = $SFOS_ARCH" >> /etc/zypp/zypp.conf

# init rpm database
rpm --root $INSTALL_ROOT --initdb

# define repositories
zypper --root $INSTALL_ROOT ar \
       https://releases.jolla.com/releases/$RELEASE/jolla-hw/adaptation-common/$SFOS_ARCH/ adaptation-common
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/jolla-apps/$RELEASE/$SFOS_ARCH/ apps
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/$RELEASE/hotfixes/$SFOS_ARCH/ hotfixes
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/$RELEASE/jolla/$SFOS_ARCH/ jolla

# install packages
zypper --gpg-auto-import-keys --non-interactive \
       --root $INSTALL_ROOT in $PACKAGES

echo -n "$SFOS_ARCH-meego-linux" > $INSTALL_ROOT/etc/rpm/platform
echo "arch = $SFOS_ARCH" >> $INSTALL_ROOT/etc/zypp/zypp.conf
echo "BUILD: SailfishOS Builder" >> $INSTALL_ROOT/etc/meego-release

# rpmtarget used by buildrpm
echo $RPMTARGET > $INSTALL_ROOT/etc/rpmtarget

# drop lastlog - Docker will just waste storage on it
rm -f $INSTALL_ROOT/var/log/lastlog
