#!/bin/bash

set -ex

if [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

SFOS_ARCH=$1
RELEASE=$2

case "$SFOS_ARCH" in
    "i486")
	RPMTARGET=i486-meego-linux
	;;
    "aarch64")
	RPMTARGET=aarch64-meego-linux
	;;
    "armv7hl")
	RPMTARGET=armv7hl-meego-linux
	;;
    *)
	echo "Unknown architecture specified:" "$SFOS_ARCH"
	exit -1
esac

INSTALL_ROOT=/sfos

# minimal set of packages for SFOS root
PACKAGES="
basesystem
gnu-bash
gnu-diffutils
gnu-findutils
gnu-grep
gnu-gzip
gnu-sed
gnu-tar
gnu-which
"

# switch arch to the desired one
echo "arch = $SFOS_ARCH" >> /etc/zypp/zypp.conf

# for some reason this is setup as a link otherwise
mkdir -p $INSTALL_ROOT/var/lib/rpm

# define repositories
zypper --root $INSTALL_ROOT ar \
       https://releases.jolla.com/releases/$RELEASE/jolla-hw/adaptation-common/$SFOS_ARCH/ adaptation-common
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/jolla-apps/$RELEASE/$SFOS_ARCH/ apps
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/$RELEASE/hotfixes/$SFOS_ARCH/ hotfixes
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/$RELEASE/jolla/$SFOS_ARCH/ jolla

# install packages - make sure that preferred gnu utils will be added first
zypper --gpg-auto-import-keys --non-interactive \
       --root $INSTALL_ROOT in $PACKAGES

# install rpm and zypper
zypper --non-interactive \
       --root $INSTALL_ROOT in rpm || echo "Ignoring error with RPM lock"

zypper --non-interactive \
       --root $INSTALL_ROOT in zypper

# setting up variables
echo -n "$SFOS_ARCH-meego-linux" > $INSTALL_ROOT/etc/rpm/platform
#echo "arch = $SFOS_ARCH" >> $INSTALL_ROOT/etc/zypp/zypp.conf
echo "BUILD: SailfishOS Builder" >> $INSTALL_ROOT/etc/meego-release

# rpmtarget used by buildrpm
echo $RPMTARGET > $INSTALL_ROOT/etc/rpmtarget
