#!/bin/bash

set -ex

INSTALL_ROOT=/sfos

# packages that have to be installed later:
# - git (otherwise %posttrans script 'filesystem' will fail on armv7hl

PACKAGES="
atruncate
attr
basesystem
gcc-c++
gnu-bash
gnu-coreutils
gnu-cpio
gnu-diffutils
gnu-findutils
gnu-grep
gnu-gzip
gnu-sed
gnu-tar
gnu-which
deltarpm
file
jolla-ca
kbd
make
meego-rpm-config
net-tools
passwd
pigz
procps-ng
psmisc-tools
python3-pip
rootfiles
rpm-build
rpmlint
sailfish-ca
shadow-utils
util-linux
xdg-utils
zypper
"

# switch arch to the desired one
echo "arch = @ARCH@" >> /etc/zypp/zypp.conf

# init rpm database
rpm --root $INSTALL_ROOT --initdb

# define repositories
zypper --root $INSTALL_ROOT ar \
       https://releases.jolla.com/releases/@RELEASE@/jolla-hw/adaptation-common/@ARCH@/ adaptation-common
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/jolla-apps/@RELEASE@/@ARCH@/ apps
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/@RELEASE@/hotfixes/@ARCH@/ hotfixes
zypper --root $INSTALL_ROOT ar https://releases.jolla.com/releases/@RELEASE@/jolla/@ARCH@/ jolla

# install packages
zypper --gpg-auto-import-keys --non-interactive \
       --root $INSTALL_ROOT in $PACKAGES

echo -n "@ARCH@-meego-linux" > $INSTALL_ROOT/etc/rpm/platform
echo "arch = @ARCH@" >> $INSTALL_ROOT/etc/zypp/zypp.conf
echo "BUILD: SailfishOS Builder" >> $INSTALL_ROOT/etc/meego-release

# rpmtarget used by buildrpm
echo @RPMTARGET@ > $INSTALL_ROOT/etc/rpmtarget

# drop lastlog - Docker will just waste storage on it
rm -f $INSTALL_ROOT/var/log/lastlog
